server:
  port: 8080
  servlet:
    context-path: /springboot-monitor # 项目加载路径

#logging:
#  level: # 日志级别，key为包名，value为具体的级别
#    com: error
#    org.springframework: debug
##  file: # 日志 file 与 path，两者冲突，均不指定时，默认控制台输出
##    name: C:/Users/Alex/Desktop/test.log # 输出到xxx.log文件
##    path: C:/Users/Alex/Desktop # 输出到指定目录的spring.log文件
#  pattern:
#    console: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n" # 控制台输出的日志格式
#    file: "%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n" # 日志输出的格式

#debug: true # 控制台打印自动配置报告

# 监控审计
management:
  endpoints: # 要暴露的端点
    web:
      base-path: /actuator  # Endpoint 基础路径，默认是 /actuator
      exposure:
        # exclude: '*'   exclude 的优先级高于 include，
        include: ["auditevents","health","info","beans","scheduledtasks"]

  endpoint: # 开启暴露的端点
    auditevents: # 显示应用暴露的审计事件
      enabled: true
      cache:
        time-to-live: 10s # 配置端点缓存响应的时间
    info: # 应用基本信息
      enabled: true
    health: # 健康信息
      enabled: true
      show-details: always # 显示详细信息
    beans: # Bean 的完整列表
      enabled: true
    scheduledtasks: #计划任务
      enabled: true

