server:
  port: 8003

spring:
  application:
    # 微服务名称
    name: payment-service-eureka
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud03
    username: root
    password: 123456

mybatis-plus:
  # xxxMapper.xml 文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 驼峰映射
    map-underscore-to-camel-case: true
    # 二级缓存
    cache-enabled: true
    # 打印 SQL 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  instance:
    # 自定义Eureka客户端服务名称
    instance-id: Payment-Service-Eureka8003
    # 访问路径显示 ip
    prefer-ip-address: true
  # Eureka 服务注册
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

# 对于注册进Eureka的服务，使用SpringBoot的健康监控以自定义info信息
info:
  app.name: "SpringCloud"
  module.serviceName: ${spring.application.name}
  module.eurekaName: ${eureka.instance.instance-id}
  module.port: ${server.port}
  module.description: "生产者-支付模块，服务注册采用Eureka"
  module.author: "Alex_McAvoy"
  build.artifactId: @project.artifactId@
  build.version: @project.version@