server:
  port: 8080
  servlet:
    context-path: /springboot # 项目加载路径

  error:
    include-exception: true # 获取异常对象
    include-message: always # 获取异常消息

spring:
  thymeleaf:
    cache: false # 禁用模板引擎缓存
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/ # 修改静态资源访问路径