server:
  port: 8080
  servlet:
    context-path: /springboot # 项目加载路径

spring:
  thymeleaf:
    cache: false # 禁用模板引擎缓存
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/ # 修改静态资源访问路径
  mvc:
    hiddenmethod:
      filter:
        enabled: true # POST 伪装 PUT 和 DELETE